name: "Deploy ACA to Prd"

on:
  workflow_dispatch:
    inputs:
      app_dir:
        description: '배포할 애플리케이션 디렉토리 이름 (예: test-app, app-b)'
        required: true
        type: string

permissions:
  id-token: write # Azure 로그인을 위한 OIDC 토큰 발급 권한
  contents: read  # 저장소 코드를 읽기 위한 권한

jobs:
  deploy-prd:
    runs-on: [self-hosted, prd]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          auth-type: identity
          client-id: ${{ secrets.UAMI_CLIENT_ID_PRD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SUB_ID_PRD }}
          allow-no-subscriptions: true

      - name: Terraform Init
        working-directory: ${{ inputs.app_dir }}
        run: |
          terraform init \
            -backend-config="resource_group_name=rg-krc-prd-common" \
            -backend-config="storage_account_name=sakrcdevktcloudshell" \
            -backend-config="container_name=terraform-state" \
            -backend-config="key=prd/${{ inputs.app_dir }}/terraform.tfstate" \
            -backend-config="subscription_id=${{ secrets.SUB_ID_PRD }}"

      - name: Terraform Apply
        working-directory: ${{ inputs.app_dir }}
        run: |
          terraform apply -auto-approve \
            -var="uami_client_id=${{ secrets.UAMI_CLIENT_ID_PRD }}" \
            -var="subscription_id=${{ secrets.SUB_ID_PRD }}"