name: "Deploy ACA to Dev"

on:
  workflow_dispatch:

permissions:
  id-token: write # Azure 로그인을 위한 OIDC 토큰 발급 권한
  contents: read  # 저장소 코드를 읽기 위한 권한

jobs:
  deploy-dev:
    runs-on: self-hosted 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.UAMI_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SUB_ID_DEV }}
          allow-no-subscriptions: true

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=rg-krc-dev-common" \
            -backend-config="storage_account_name=sakrcdevktcloudshell" \
            -backend-config="container_name=terraform-state" \
            -backend-config="key=dev/terraform.tfstate" \
            -backend-config="subscription_id=${{ secrets.SUB_ID_DEV }}"

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var-file="dev.tfvars" \
            -var="uami_client_id=${{ secrets.UAMI_CLIENT_ID }}" \
            -var="subscription_id=${{ secrets.SUB_ID_DEV }}"